[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "coding-with-zikra", email = "malimzikra@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "supabase>=2.31.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
